// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: aws/aws_ecr.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Oak9.Tython.Aws.Ecr {

  /// <summary>Holder for reflection information generated from aws/aws_ecr.proto</summary>
  public static partial class AwsEcrReflection {

    #region Descriptor
    /// <summary>File descriptor for aws/aws_ecr.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AwsEcrReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFhd3MvYXdzX2Vjci5wcm90bxITb2FrOS50eXRob24uYXdzLmVjchoTc2hh",
            "cmVkL3NoYXJlZC5wcm90byKIAQoZUmVwb3NpdG9yeUxpZmVjeWNsZVBvbGlj",
            "eRI3Cg1yZXNvdXJjZV9pbmZvGAEgASgLMiAub2FrOS50eXRob24uc2hhcmVk",
            "LlJlc291cmNlSW5mbxIdChVsaWZlY3ljbGVfcG9saWN5X3RleHQYAiABKAkS",
            "EwoLcmVnaXN0cnlfaWQYAyABKAki7gQKClJlcG9zaXRvcnkSNwoNcmVzb3Vy",
            "Y2VfaW5mbxgBIAEoCzIgLm9hazkudHl0aG9uLnNoYXJlZC5SZXNvdXJjZUlu",
            "Zm8SSAoQbGlmZWN5Y2xlX3BvbGljeRgCIAEoCzIuLm9hazkudHl0aG9uLmF3",
            "cy5lY3IuUmVwb3NpdG9yeUxpZmVjeWNsZVBvbGljeRIXCg9yZXBvc2l0b3J5",
            "X25hbWUYAyABKAkSWQoWcmVwb3NpdG9yeV9wb2xpY3lfdGV4dBgEIAMoCzI5",
            "Lm9hazkudHl0aG9uLmF3cy5lY3IuUmVwb3NpdG9yeS5SZXBvc2l0b3J5UG9s",
            "aWN5VGV4dEVudHJ5EjcKBHRhZ3MYBSADKAsyKS5vYWs5LnR5dGhvbi5hd3Mu",
            "ZWNyLlJlcG9zaXRvcnkuVGFnc0VudHJ5EhwKFGltYWdlX3RhZ19tdXRhYmls",
            "aXR5GAYgASgJEmUKHGltYWdlX3NjYW5uaW5nX2NvbmZpZ3VyYXRpb24YByAD",
            "KAsyPy5vYWs5LnR5dGhvbi5hd3MuZWNyLlJlcG9zaXRvcnkuSW1hZ2VTY2Fu",
            "bmluZ0NvbmZpZ3VyYXRpb25FbnRyeRo7ChlSZXBvc2l0b3J5UG9saWN5VGV4",
            "dEVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEaKwoJVGFn",
            "c0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEaQQofSW1h",
            "Z2VTY2FubmluZ0NvbmZpZ3VyYXRpb25FbnRyeRILCgNrZXkYASABKAkSDQoF",
            "dmFsdWUYAiABKAk6AjgBIjoKA0VDUhIzCgpyZXBvc2l0b3J5GAEgAygLMh8u",
            "b2FrOS50eXRob24uYXdzLmVjci5SZXBvc2l0b3J5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Oak9.Tython.Shared.SharedReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Oak9.Tython.Aws.Ecr.RepositoryLifecyclePolicy), global::Oak9.Tython.Aws.Ecr.RepositoryLifecyclePolicy.Parser, new[]{ "ResourceInfo", "LifecyclePolicyText", "RegistryId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Oak9.Tython.Aws.Ecr.Repository), global::Oak9.Tython.Aws.Ecr.Repository.Parser, new[]{ "ResourceInfo", "LifecyclePolicy", "RepositoryName", "RepositoryPolicyText", "Tags", "ImageTagMutability", "ImageScanningConfiguration" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Oak9.Tython.Aws.Ecr.ECR), global::Oak9.Tython.Aws.Ecr.ECR.Parser, new[]{ "Repository" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RepositoryLifecyclePolicy : pb::IMessage<RepositoryLifecyclePolicy>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RepositoryLifecyclePolicy> _parser = new pb::MessageParser<RepositoryLifecyclePolicy>(() => new RepositoryLifecyclePolicy());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RepositoryLifecyclePolicy> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oak9.Tython.Aws.Ecr.AwsEcrReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RepositoryLifecyclePolicy() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RepositoryLifecyclePolicy(RepositoryLifecyclePolicy other) : this() {
      resourceInfo_ = other.resourceInfo_ != null ? other.resourceInfo_.Clone() : null;
      lifecyclePolicyText_ = other.lifecyclePolicyText_;
      registryId_ = other.registryId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RepositoryLifecyclePolicy Clone() {
      return new RepositoryLifecyclePolicy(this);
    }

    /// <summary>Field number for the "resource_info" field.</summary>
    public const int ResourceInfoFieldNumber = 1;
    private global::Oak9.Tython.Shared.ResourceInfo resourceInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oak9.Tython.Shared.ResourceInfo ResourceInfo {
      get { return resourceInfo_; }
      set {
        resourceInfo_ = value;
      }
    }

    /// <summary>Field number for the "lifecycle_policy_text" field.</summary>
    public const int LifecyclePolicyTextFieldNumber = 2;
    private string lifecyclePolicyText_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LifecyclePolicyText {
      get { return lifecyclePolicyText_; }
      set {
        lifecyclePolicyText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "registry_id" field.</summary>
    public const int RegistryIdFieldNumber = 3;
    private string registryId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RegistryId {
      get { return registryId_; }
      set {
        registryId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RepositoryLifecyclePolicy);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RepositoryLifecyclePolicy other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ResourceInfo, other.ResourceInfo)) return false;
      if (LifecyclePolicyText != other.LifecyclePolicyText) return false;
      if (RegistryId != other.RegistryId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (resourceInfo_ != null) hash ^= ResourceInfo.GetHashCode();
      if (LifecyclePolicyText.Length != 0) hash ^= LifecyclePolicyText.GetHashCode();
      if (RegistryId.Length != 0) hash ^= RegistryId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (resourceInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ResourceInfo);
      }
      if (LifecyclePolicyText.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LifecyclePolicyText);
      }
      if (RegistryId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RegistryId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (resourceInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ResourceInfo);
      }
      if (LifecyclePolicyText.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LifecyclePolicyText);
      }
      if (RegistryId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RegistryId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (resourceInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResourceInfo);
      }
      if (LifecyclePolicyText.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LifecyclePolicyText);
      }
      if (RegistryId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RegistryId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RepositoryLifecyclePolicy other) {
      if (other == null) {
        return;
      }
      if (other.resourceInfo_ != null) {
        if (resourceInfo_ == null) {
          ResourceInfo = new global::Oak9.Tython.Shared.ResourceInfo();
        }
        ResourceInfo.MergeFrom(other.ResourceInfo);
      }
      if (other.LifecyclePolicyText.Length != 0) {
        LifecyclePolicyText = other.LifecyclePolicyText;
      }
      if (other.RegistryId.Length != 0) {
        RegistryId = other.RegistryId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (resourceInfo_ == null) {
              ResourceInfo = new global::Oak9.Tython.Shared.ResourceInfo();
            }
            input.ReadMessage(ResourceInfo);
            break;
          }
          case 18: {
            LifecyclePolicyText = input.ReadString();
            break;
          }
          case 26: {
            RegistryId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (resourceInfo_ == null) {
              ResourceInfo = new global::Oak9.Tython.Shared.ResourceInfo();
            }
            input.ReadMessage(ResourceInfo);
            break;
          }
          case 18: {
            LifecyclePolicyText = input.ReadString();
            break;
          }
          case 26: {
            RegistryId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Repository : pb::IMessage<Repository>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Repository> _parser = new pb::MessageParser<Repository>(() => new Repository());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Repository> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oak9.Tython.Aws.Ecr.AwsEcrReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Repository() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Repository(Repository other) : this() {
      resourceInfo_ = other.resourceInfo_ != null ? other.resourceInfo_.Clone() : null;
      lifecyclePolicy_ = other.lifecyclePolicy_ != null ? other.lifecyclePolicy_.Clone() : null;
      repositoryName_ = other.repositoryName_;
      repositoryPolicyText_ = other.repositoryPolicyText_.Clone();
      tags_ = other.tags_.Clone();
      imageTagMutability_ = other.imageTagMutability_;
      imageScanningConfiguration_ = other.imageScanningConfiguration_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Repository Clone() {
      return new Repository(this);
    }

    /// <summary>Field number for the "resource_info" field.</summary>
    public const int ResourceInfoFieldNumber = 1;
    private global::Oak9.Tython.Shared.ResourceInfo resourceInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oak9.Tython.Shared.ResourceInfo ResourceInfo {
      get { return resourceInfo_; }
      set {
        resourceInfo_ = value;
      }
    }

    /// <summary>Field number for the "lifecycle_policy" field.</summary>
    public const int LifecyclePolicyFieldNumber = 2;
    private global::Oak9.Tython.Aws.Ecr.RepositoryLifecyclePolicy lifecyclePolicy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Oak9.Tython.Aws.Ecr.RepositoryLifecyclePolicy LifecyclePolicy {
      get { return lifecyclePolicy_; }
      set {
        lifecyclePolicy_ = value;
      }
    }

    /// <summary>Field number for the "repository_name" field.</summary>
    public const int RepositoryNameFieldNumber = 3;
    private string repositoryName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RepositoryName {
      get { return repositoryName_; }
      set {
        repositoryName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "repository_policy_text" field.</summary>
    public const int RepositoryPolicyTextFieldNumber = 4;
    private static readonly pbc::MapField<string, string>.Codec _map_repositoryPolicyText_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 34);
    private readonly pbc::MapField<string, string> repositoryPolicyText_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> RepositoryPolicyText {
      get { return repositoryPolicyText_; }
    }

    /// <summary>Field number for the "tags" field.</summary>
    public const int TagsFieldNumber = 5;
    private static readonly pbc::MapField<string, string>.Codec _map_tags_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 42);
    private readonly pbc::MapField<string, string> tags_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Tags {
      get { return tags_; }
    }

    /// <summary>Field number for the "image_tag_mutability" field.</summary>
    public const int ImageTagMutabilityFieldNumber = 6;
    private string imageTagMutability_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ImageTagMutability {
      get { return imageTagMutability_; }
      set {
        imageTagMutability_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "image_scanning_configuration" field.</summary>
    public const int ImageScanningConfigurationFieldNumber = 7;
    private static readonly pbc::MapField<string, string>.Codec _map_imageScanningConfiguration_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 58);
    private readonly pbc::MapField<string, string> imageScanningConfiguration_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> ImageScanningConfiguration {
      get { return imageScanningConfiguration_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Repository);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Repository other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ResourceInfo, other.ResourceInfo)) return false;
      if (!object.Equals(LifecyclePolicy, other.LifecyclePolicy)) return false;
      if (RepositoryName != other.RepositoryName) return false;
      if (!RepositoryPolicyText.Equals(other.RepositoryPolicyText)) return false;
      if (!Tags.Equals(other.Tags)) return false;
      if (ImageTagMutability != other.ImageTagMutability) return false;
      if (!ImageScanningConfiguration.Equals(other.ImageScanningConfiguration)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (resourceInfo_ != null) hash ^= ResourceInfo.GetHashCode();
      if (lifecyclePolicy_ != null) hash ^= LifecyclePolicy.GetHashCode();
      if (RepositoryName.Length != 0) hash ^= RepositoryName.GetHashCode();
      hash ^= RepositoryPolicyText.GetHashCode();
      hash ^= Tags.GetHashCode();
      if (ImageTagMutability.Length != 0) hash ^= ImageTagMutability.GetHashCode();
      hash ^= ImageScanningConfiguration.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (resourceInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ResourceInfo);
      }
      if (lifecyclePolicy_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LifecyclePolicy);
      }
      if (RepositoryName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RepositoryName);
      }
      repositoryPolicyText_.WriteTo(output, _map_repositoryPolicyText_codec);
      tags_.WriteTo(output, _map_tags_codec);
      if (ImageTagMutability.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ImageTagMutability);
      }
      imageScanningConfiguration_.WriteTo(output, _map_imageScanningConfiguration_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (resourceInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ResourceInfo);
      }
      if (lifecyclePolicy_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LifecyclePolicy);
      }
      if (RepositoryName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RepositoryName);
      }
      repositoryPolicyText_.WriteTo(ref output, _map_repositoryPolicyText_codec);
      tags_.WriteTo(ref output, _map_tags_codec);
      if (ImageTagMutability.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ImageTagMutability);
      }
      imageScanningConfiguration_.WriteTo(ref output, _map_imageScanningConfiguration_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (resourceInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResourceInfo);
      }
      if (lifecyclePolicy_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LifecyclePolicy);
      }
      if (RepositoryName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RepositoryName);
      }
      size += repositoryPolicyText_.CalculateSize(_map_repositoryPolicyText_codec);
      size += tags_.CalculateSize(_map_tags_codec);
      if (ImageTagMutability.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageTagMutability);
      }
      size += imageScanningConfiguration_.CalculateSize(_map_imageScanningConfiguration_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Repository other) {
      if (other == null) {
        return;
      }
      if (other.resourceInfo_ != null) {
        if (resourceInfo_ == null) {
          ResourceInfo = new global::Oak9.Tython.Shared.ResourceInfo();
        }
        ResourceInfo.MergeFrom(other.ResourceInfo);
      }
      if (other.lifecyclePolicy_ != null) {
        if (lifecyclePolicy_ == null) {
          LifecyclePolicy = new global::Oak9.Tython.Aws.Ecr.RepositoryLifecyclePolicy();
        }
        LifecyclePolicy.MergeFrom(other.LifecyclePolicy);
      }
      if (other.RepositoryName.Length != 0) {
        RepositoryName = other.RepositoryName;
      }
      repositoryPolicyText_.MergeFrom(other.repositoryPolicyText_);
      tags_.MergeFrom(other.tags_);
      if (other.ImageTagMutability.Length != 0) {
        ImageTagMutability = other.ImageTagMutability;
      }
      imageScanningConfiguration_.MergeFrom(other.imageScanningConfiguration_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (resourceInfo_ == null) {
              ResourceInfo = new global::Oak9.Tython.Shared.ResourceInfo();
            }
            input.ReadMessage(ResourceInfo);
            break;
          }
          case 18: {
            if (lifecyclePolicy_ == null) {
              LifecyclePolicy = new global::Oak9.Tython.Aws.Ecr.RepositoryLifecyclePolicy();
            }
            input.ReadMessage(LifecyclePolicy);
            break;
          }
          case 26: {
            RepositoryName = input.ReadString();
            break;
          }
          case 34: {
            repositoryPolicyText_.AddEntriesFrom(input, _map_repositoryPolicyText_codec);
            break;
          }
          case 42: {
            tags_.AddEntriesFrom(input, _map_tags_codec);
            break;
          }
          case 50: {
            ImageTagMutability = input.ReadString();
            break;
          }
          case 58: {
            imageScanningConfiguration_.AddEntriesFrom(input, _map_imageScanningConfiguration_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (resourceInfo_ == null) {
              ResourceInfo = new global::Oak9.Tython.Shared.ResourceInfo();
            }
            input.ReadMessage(ResourceInfo);
            break;
          }
          case 18: {
            if (lifecyclePolicy_ == null) {
              LifecyclePolicy = new global::Oak9.Tython.Aws.Ecr.RepositoryLifecyclePolicy();
            }
            input.ReadMessage(LifecyclePolicy);
            break;
          }
          case 26: {
            RepositoryName = input.ReadString();
            break;
          }
          case 34: {
            repositoryPolicyText_.AddEntriesFrom(ref input, _map_repositoryPolicyText_codec);
            break;
          }
          case 42: {
            tags_.AddEntriesFrom(ref input, _map_tags_codec);
            break;
          }
          case 50: {
            ImageTagMutability = input.ReadString();
            break;
          }
          case 58: {
            imageScanningConfiguration_.AddEntriesFrom(ref input, _map_imageScanningConfiguration_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ECR : pb::IMessage<ECR>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ECR> _parser = new pb::MessageParser<ECR>(() => new ECR());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ECR> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Oak9.Tython.Aws.Ecr.AwsEcrReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ECR() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ECR(ECR other) : this() {
      repository_ = other.repository_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ECR Clone() {
      return new ECR(this);
    }

    /// <summary>Field number for the "repository" field.</summary>
    public const int RepositoryFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Oak9.Tython.Aws.Ecr.Repository> _repeated_repository_codec
        = pb::FieldCodec.ForMessage(10, global::Oak9.Tython.Aws.Ecr.Repository.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.Aws.Ecr.Repository> repository_ = new pbc::RepeatedField<global::Oak9.Tython.Aws.Ecr.Repository>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.Aws.Ecr.Repository> Repository {
      get { return repository_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ECR);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ECR other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!repository_.Equals(other.repository_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= repository_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      repository_.WriteTo(output, _repeated_repository_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      repository_.WriteTo(ref output, _repeated_repository_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += repository_.CalculateSize(_repeated_repository_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ECR other) {
      if (other == null) {
        return;
      }
      repository_.Add(other.repository_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            repository_.AddEntriesFrom(input, _repeated_repository_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            repository_.AddEntriesFrom(ref input, _repeated_repository_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
