// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: kubernetes/kubernetes_kubernetes_namespaced_bundle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SacKubernetes.KubernetesNamespacedBundle {

  /// <summary>Holder for reflection information generated from kubernetes/kubernetes_kubernetes_namespaced_bundle.proto</summary>
  public static partial class KubernetesKubernetesNamespacedBundleReflection {

    #region Descriptor
    /// <summary>File descriptor for kubernetes/kubernetes_kubernetes_namespaced_bundle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KubernetesKubernetesNamespacedBundleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjhrdWJlcm5ldGVzL2t1YmVybmV0ZXNfa3ViZXJuZXRlc19uYW1lc3BhY2Vk",
            "X2J1bmRsZS5wcm90bxIrc2FjX2t1YmVybmV0ZXMua3ViZXJuZXRlc19uYW1l",
            "c3BhY2VkX2J1bmRsZRoTc2hhcmVkL3NoYXJlZC5wcm90bxoua3ViZXJuZXRl",
            "cy9rdWJlcm5ldGVzX2lvLms4cy5hcGkuY29yZS52MS5wcm90bxoua3ViZXJu",
            "ZXRlcy9rdWJlcm5ldGVzX2lvLms4cy5hcGkuYXBwcy52MS5wcm90bxo1a3Vi",
            "ZXJuZXRlcy9rdWJlcm5ldGVzX2lvLms4cy5hcGkuYXV0b3NjYWxpbmcudjIu",
            "cHJvdG8aLmt1YmVybmV0ZXMva3ViZXJuZXRlc19pby5rOHMuYXBpLnJiYWMu",
            "djEucHJvdG8aNGt1YmVybmV0ZXMva3ViZXJuZXRlc19pby5rOHMuYXBpLm5l",
            "dHdvcmtpbmcudjEucHJvdG8i+gcKFUt1YmVybmV0ZXNfTmFtZXNwYWNlZBI1",
            "CgdiaW5kaW5nGAEgAygLMiQub2FrOS50eXRob24uazhzLmFwaS5jb3JlLnYx",
            "LkJpbmRpbmcSOgoKY29uZmlnX21hcBgCIAMoCzImLm9hazkudHl0aG9uLms4",
            "cy5hcGkuY29yZS52MS5Db25maWdNYXASLQoDcG9kGAMgAygLMiAub2FrOS50",
            "eXRob24uazhzLmFwaS5jb3JlLnYxLlBvZBJECg9zZXJ2aWNlX2FjY291bnQY",
            "BCADKAsyKy5vYWs5LnR5dGhvbi5rOHMuYXBpLmNvcmUudjEuU2VydmljZUFj",
            "Y291bnQSNQoHc2VydmljZRgFIAMoCzIkLm9hazkudHl0aG9uLms4cy5hcGku",
            "Y29yZS52MS5TZXJ2aWNlEjoKCmRhZW1vbl9zZXQYBiADKAsyJi5vYWs5LnR5",
            "dGhvbi5rOHMuYXBpLmFwcHMudjEuRGFlbW9uU2V0EjsKCmRlcGxveW1lbnQY",
            "ByADKAsyJy5vYWs5LnR5dGhvbi5rOHMuYXBpLmFwcHMudjEuRGVwbG95bWVu",
            "dBI8CgtyZXBsaWNhX3NldBgIIAMoCzInLm9hazkudHl0aG9uLms4cy5hcGku",
            "YXBwcy52MS5SZXBsaWNhU2V0Ej4KDHN0YXRlZnVsX3NldBgJIAMoCzIoLm9h",
            "azkudHl0aG9uLms4cy5hcGkuYXBwcy52MS5TdGF0ZWZ1bFNldBJeChlob3Jp",
            "em9udGFsX3BvZF9hdXRvc2NhbGVyGAogAygLMjsub2FrOS50eXRob24uazhz",
            "LmFwaS5hdXRvc2NhbGluZy52Mi5Ib3Jpem9udGFsUG9kQXV0b3NjYWxlchI+",
            "Cgxwb2RfdGVtcGxhdGUYCyADKAsyKC5vYWs5LnR5dGhvbi5rOHMuYXBpLmNv",
            "cmUudjEuUG9kVGVtcGxhdGUSMwoGc2VjcmV0GAwgAygLMiMub2FrOS50eXRo",
            "b24uazhzLmFwaS5jb3JlLnYxLlNlY3JldBI+Cgxyb2xlX2JpbmRpbmcYDSAD",
            "KAsyKC5vYWs5LnR5dGhvbi5rOHMuYXBpLnJiYWMudjEuUm9sZUJpbmRpbmcS",
            "LwoEcm9sZRgOIAMoCzIhLm9hazkudHl0aG9uLms4cy5hcGkucmJhYy52MS5S",
            "b2xlEjsKB2luZ3Jlc3MYDyADKAsyKi5vYWs5LnR5dGhvbi5rOHMuYXBpLm5l",
            "dHdvcmtpbmcudjEuSW5ncmVzcxJICg5uZXR3b3JrX3BvbGljeRgQIAMoCzIw",
            "Lm9hazkudHl0aG9uLms4cy5hcGkubmV0d29ya2luZy52MS5OZXR3b3JrUG9s",
            "aWN5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Oak9.Tython.Shared.SharedReflection.Descriptor, global::Oak9.Tython.K8S.Api.Core.V1.KubernetesIoK8SApiCoreV1Reflection.Descriptor, global::Oak9.Tython.K8S.Api.Apps.V1.KubernetesIoK8SApiAppsV1Reflection.Descriptor, global::Oak9.Tython.K8S.Api.Autoscaling.V2.KubernetesIoK8SApiAutoscalingV2Reflection.Descriptor, global::Oak9.Tython.K8S.Api.Rbac.V1.KubernetesIoK8SApiRbacV1Reflection.Descriptor, global::Oak9.Tython.K8S.Api.Networking.V1.KubernetesIoK8SApiNetworkingV1Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SacKubernetes.KubernetesNamespacedBundle.Kubernetes_Namespaced), global::SacKubernetes.KubernetesNamespacedBundle.Kubernetes_Namespaced.Parser, new[]{ "Binding", "ConfigMap", "Pod", "ServiceAccount", "Service", "DaemonSet", "Deployment", "ReplicaSet", "StatefulSet", "HorizontalPodAutoscaler", "PodTemplate", "Secret", "RoleBinding", "Role", "Ingress", "NetworkPolicy" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Kubernetes_Namespaced : pb::IMessage<Kubernetes_Namespaced>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Kubernetes_Namespaced> _parser = new pb::MessageParser<Kubernetes_Namespaced>(() => new Kubernetes_Namespaced());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Kubernetes_Namespaced> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SacKubernetes.KubernetesNamespacedBundle.KubernetesKubernetesNamespacedBundleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Kubernetes_Namespaced() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Kubernetes_Namespaced(Kubernetes_Namespaced other) : this() {
      binding_ = other.binding_.Clone();
      configMap_ = other.configMap_.Clone();
      pod_ = other.pod_.Clone();
      serviceAccount_ = other.serviceAccount_.Clone();
      service_ = other.service_.Clone();
      daemonSet_ = other.daemonSet_.Clone();
      deployment_ = other.deployment_.Clone();
      replicaSet_ = other.replicaSet_.Clone();
      statefulSet_ = other.statefulSet_.Clone();
      horizontalPodAutoscaler_ = other.horizontalPodAutoscaler_.Clone();
      podTemplate_ = other.podTemplate_.Clone();
      secret_ = other.secret_.Clone();
      roleBinding_ = other.roleBinding_.Clone();
      role_ = other.role_.Clone();
      ingress_ = other.ingress_.Clone();
      networkPolicy_ = other.networkPolicy_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Kubernetes_Namespaced Clone() {
      return new Kubernetes_Namespaced(this);
    }

    /// <summary>Field number for the "binding" field.</summary>
    public const int BindingFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Core.V1.Binding> _repeated_binding_codec
        = pb::FieldCodec.ForMessage(10, global::Oak9.Tython.K8S.Api.Core.V1.Binding.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Binding> binding_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Binding>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Binding> Binding {
      get { return binding_; }
    }

    /// <summary>Field number for the "config_map" field.</summary>
    public const int ConfigMapFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Core.V1.ConfigMap> _repeated_configMap_codec
        = pb::FieldCodec.ForMessage(18, global::Oak9.Tython.K8S.Api.Core.V1.ConfigMap.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.ConfigMap> configMap_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.ConfigMap>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.ConfigMap> ConfigMap {
      get { return configMap_; }
    }

    /// <summary>Field number for the "pod" field.</summary>
    public const int PodFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Core.V1.Pod> _repeated_pod_codec
        = pb::FieldCodec.ForMessage(26, global::Oak9.Tython.K8S.Api.Core.V1.Pod.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Pod> pod_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Pod>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Pod> Pod {
      get { return pod_; }
    }

    /// <summary>Field number for the "service_account" field.</summary>
    public const int ServiceAccountFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Core.V1.ServiceAccount> _repeated_serviceAccount_codec
        = pb::FieldCodec.ForMessage(34, global::Oak9.Tython.K8S.Api.Core.V1.ServiceAccount.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.ServiceAccount> serviceAccount_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.ServiceAccount>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.ServiceAccount> ServiceAccount {
      get { return serviceAccount_; }
    }

    /// <summary>Field number for the "service" field.</summary>
    public const int ServiceFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Core.V1.Service> _repeated_service_codec
        = pb::FieldCodec.ForMessage(42, global::Oak9.Tython.K8S.Api.Core.V1.Service.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Service> service_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Service>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Service> Service {
      get { return service_; }
    }

    /// <summary>Field number for the "daemon_set" field.</summary>
    public const int DaemonSetFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Apps.V1.DaemonSet> _repeated_daemonSet_codec
        = pb::FieldCodec.ForMessage(50, global::Oak9.Tython.K8S.Api.Apps.V1.DaemonSet.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.DaemonSet> daemonSet_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.DaemonSet>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.DaemonSet> DaemonSet {
      get { return daemonSet_; }
    }

    /// <summary>Field number for the "deployment" field.</summary>
    public const int DeploymentFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Apps.V1.Deployment> _repeated_deployment_codec
        = pb::FieldCodec.ForMessage(58, global::Oak9.Tython.K8S.Api.Apps.V1.Deployment.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.Deployment> deployment_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.Deployment>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.Deployment> Deployment {
      get { return deployment_; }
    }

    /// <summary>Field number for the "replica_set" field.</summary>
    public const int ReplicaSetFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Apps.V1.ReplicaSet> _repeated_replicaSet_codec
        = pb::FieldCodec.ForMessage(66, global::Oak9.Tython.K8S.Api.Apps.V1.ReplicaSet.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.ReplicaSet> replicaSet_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.ReplicaSet>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.ReplicaSet> ReplicaSet {
      get { return replicaSet_; }
    }

    /// <summary>Field number for the "stateful_set" field.</summary>
    public const int StatefulSetFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Apps.V1.StatefulSet> _repeated_statefulSet_codec
        = pb::FieldCodec.ForMessage(74, global::Oak9.Tython.K8S.Api.Apps.V1.StatefulSet.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.StatefulSet> statefulSet_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.StatefulSet>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Apps.V1.StatefulSet> StatefulSet {
      get { return statefulSet_; }
    }

    /// <summary>Field number for the "horizontal_pod_autoscaler" field.</summary>
    public const int HorizontalPodAutoscalerFieldNumber = 10;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Autoscaling.V2.HorizontalPodAutoscaler> _repeated_horizontalPodAutoscaler_codec
        = pb::FieldCodec.ForMessage(82, global::Oak9.Tython.K8S.Api.Autoscaling.V2.HorizontalPodAutoscaler.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Autoscaling.V2.HorizontalPodAutoscaler> horizontalPodAutoscaler_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Autoscaling.V2.HorizontalPodAutoscaler>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Autoscaling.V2.HorizontalPodAutoscaler> HorizontalPodAutoscaler {
      get { return horizontalPodAutoscaler_; }
    }

    /// <summary>Field number for the "pod_template" field.</summary>
    public const int PodTemplateFieldNumber = 11;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Core.V1.PodTemplate> _repeated_podTemplate_codec
        = pb::FieldCodec.ForMessage(90, global::Oak9.Tython.K8S.Api.Core.V1.PodTemplate.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.PodTemplate> podTemplate_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.PodTemplate>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.PodTemplate> PodTemplate {
      get { return podTemplate_; }
    }

    /// <summary>Field number for the "secret" field.</summary>
    public const int SecretFieldNumber = 12;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Core.V1.Secret> _repeated_secret_codec
        = pb::FieldCodec.ForMessage(98, global::Oak9.Tython.K8S.Api.Core.V1.Secret.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Secret> secret_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Secret>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Core.V1.Secret> Secret {
      get { return secret_; }
    }

    /// <summary>Field number for the "role_binding" field.</summary>
    public const int RoleBindingFieldNumber = 13;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Rbac.V1.RoleBinding> _repeated_roleBinding_codec
        = pb::FieldCodec.ForMessage(106, global::Oak9.Tython.K8S.Api.Rbac.V1.RoleBinding.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Rbac.V1.RoleBinding> roleBinding_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Rbac.V1.RoleBinding>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Rbac.V1.RoleBinding> RoleBinding {
      get { return roleBinding_; }
    }

    /// <summary>Field number for the "role" field.</summary>
    public const int RoleFieldNumber = 14;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Rbac.V1.Role> _repeated_role_codec
        = pb::FieldCodec.ForMessage(114, global::Oak9.Tython.K8S.Api.Rbac.V1.Role.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Rbac.V1.Role> role_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Rbac.V1.Role>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Rbac.V1.Role> Role {
      get { return role_; }
    }

    /// <summary>Field number for the "ingress" field.</summary>
    public const int IngressFieldNumber = 15;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Networking.V1.Ingress> _repeated_ingress_codec
        = pb::FieldCodec.ForMessage(122, global::Oak9.Tython.K8S.Api.Networking.V1.Ingress.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Networking.V1.Ingress> ingress_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Networking.V1.Ingress>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Networking.V1.Ingress> Ingress {
      get { return ingress_; }
    }

    /// <summary>Field number for the "network_policy" field.</summary>
    public const int NetworkPolicyFieldNumber = 16;
    private static readonly pb::FieldCodec<global::Oak9.Tython.K8S.Api.Networking.V1.NetworkPolicy> _repeated_networkPolicy_codec
        = pb::FieldCodec.ForMessage(130, global::Oak9.Tython.K8S.Api.Networking.V1.NetworkPolicy.Parser);
    private readonly pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Networking.V1.NetworkPolicy> networkPolicy_ = new pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Networking.V1.NetworkPolicy>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Oak9.Tython.K8S.Api.Networking.V1.NetworkPolicy> NetworkPolicy {
      get { return networkPolicy_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Kubernetes_Namespaced);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Kubernetes_Namespaced other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!binding_.Equals(other.binding_)) return false;
      if(!configMap_.Equals(other.configMap_)) return false;
      if(!pod_.Equals(other.pod_)) return false;
      if(!serviceAccount_.Equals(other.serviceAccount_)) return false;
      if(!service_.Equals(other.service_)) return false;
      if(!daemonSet_.Equals(other.daemonSet_)) return false;
      if(!deployment_.Equals(other.deployment_)) return false;
      if(!replicaSet_.Equals(other.replicaSet_)) return false;
      if(!statefulSet_.Equals(other.statefulSet_)) return false;
      if(!horizontalPodAutoscaler_.Equals(other.horizontalPodAutoscaler_)) return false;
      if(!podTemplate_.Equals(other.podTemplate_)) return false;
      if(!secret_.Equals(other.secret_)) return false;
      if(!roleBinding_.Equals(other.roleBinding_)) return false;
      if(!role_.Equals(other.role_)) return false;
      if(!ingress_.Equals(other.ingress_)) return false;
      if(!networkPolicy_.Equals(other.networkPolicy_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= binding_.GetHashCode();
      hash ^= configMap_.GetHashCode();
      hash ^= pod_.GetHashCode();
      hash ^= serviceAccount_.GetHashCode();
      hash ^= service_.GetHashCode();
      hash ^= daemonSet_.GetHashCode();
      hash ^= deployment_.GetHashCode();
      hash ^= replicaSet_.GetHashCode();
      hash ^= statefulSet_.GetHashCode();
      hash ^= horizontalPodAutoscaler_.GetHashCode();
      hash ^= podTemplate_.GetHashCode();
      hash ^= secret_.GetHashCode();
      hash ^= roleBinding_.GetHashCode();
      hash ^= role_.GetHashCode();
      hash ^= ingress_.GetHashCode();
      hash ^= networkPolicy_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      binding_.WriteTo(output, _repeated_binding_codec);
      configMap_.WriteTo(output, _repeated_configMap_codec);
      pod_.WriteTo(output, _repeated_pod_codec);
      serviceAccount_.WriteTo(output, _repeated_serviceAccount_codec);
      service_.WriteTo(output, _repeated_service_codec);
      daemonSet_.WriteTo(output, _repeated_daemonSet_codec);
      deployment_.WriteTo(output, _repeated_deployment_codec);
      replicaSet_.WriteTo(output, _repeated_replicaSet_codec);
      statefulSet_.WriteTo(output, _repeated_statefulSet_codec);
      horizontalPodAutoscaler_.WriteTo(output, _repeated_horizontalPodAutoscaler_codec);
      podTemplate_.WriteTo(output, _repeated_podTemplate_codec);
      secret_.WriteTo(output, _repeated_secret_codec);
      roleBinding_.WriteTo(output, _repeated_roleBinding_codec);
      role_.WriteTo(output, _repeated_role_codec);
      ingress_.WriteTo(output, _repeated_ingress_codec);
      networkPolicy_.WriteTo(output, _repeated_networkPolicy_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      binding_.WriteTo(ref output, _repeated_binding_codec);
      configMap_.WriteTo(ref output, _repeated_configMap_codec);
      pod_.WriteTo(ref output, _repeated_pod_codec);
      serviceAccount_.WriteTo(ref output, _repeated_serviceAccount_codec);
      service_.WriteTo(ref output, _repeated_service_codec);
      daemonSet_.WriteTo(ref output, _repeated_daemonSet_codec);
      deployment_.WriteTo(ref output, _repeated_deployment_codec);
      replicaSet_.WriteTo(ref output, _repeated_replicaSet_codec);
      statefulSet_.WriteTo(ref output, _repeated_statefulSet_codec);
      horizontalPodAutoscaler_.WriteTo(ref output, _repeated_horizontalPodAutoscaler_codec);
      podTemplate_.WriteTo(ref output, _repeated_podTemplate_codec);
      secret_.WriteTo(ref output, _repeated_secret_codec);
      roleBinding_.WriteTo(ref output, _repeated_roleBinding_codec);
      role_.WriteTo(ref output, _repeated_role_codec);
      ingress_.WriteTo(ref output, _repeated_ingress_codec);
      networkPolicy_.WriteTo(ref output, _repeated_networkPolicy_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += binding_.CalculateSize(_repeated_binding_codec);
      size += configMap_.CalculateSize(_repeated_configMap_codec);
      size += pod_.CalculateSize(_repeated_pod_codec);
      size += serviceAccount_.CalculateSize(_repeated_serviceAccount_codec);
      size += service_.CalculateSize(_repeated_service_codec);
      size += daemonSet_.CalculateSize(_repeated_daemonSet_codec);
      size += deployment_.CalculateSize(_repeated_deployment_codec);
      size += replicaSet_.CalculateSize(_repeated_replicaSet_codec);
      size += statefulSet_.CalculateSize(_repeated_statefulSet_codec);
      size += horizontalPodAutoscaler_.CalculateSize(_repeated_horizontalPodAutoscaler_codec);
      size += podTemplate_.CalculateSize(_repeated_podTemplate_codec);
      size += secret_.CalculateSize(_repeated_secret_codec);
      size += roleBinding_.CalculateSize(_repeated_roleBinding_codec);
      size += role_.CalculateSize(_repeated_role_codec);
      size += ingress_.CalculateSize(_repeated_ingress_codec);
      size += networkPolicy_.CalculateSize(_repeated_networkPolicy_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Kubernetes_Namespaced other) {
      if (other == null) {
        return;
      }
      binding_.Add(other.binding_);
      configMap_.Add(other.configMap_);
      pod_.Add(other.pod_);
      serviceAccount_.Add(other.serviceAccount_);
      service_.Add(other.service_);
      daemonSet_.Add(other.daemonSet_);
      deployment_.Add(other.deployment_);
      replicaSet_.Add(other.replicaSet_);
      statefulSet_.Add(other.statefulSet_);
      horizontalPodAutoscaler_.Add(other.horizontalPodAutoscaler_);
      podTemplate_.Add(other.podTemplate_);
      secret_.Add(other.secret_);
      roleBinding_.Add(other.roleBinding_);
      role_.Add(other.role_);
      ingress_.Add(other.ingress_);
      networkPolicy_.Add(other.networkPolicy_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            binding_.AddEntriesFrom(input, _repeated_binding_codec);
            break;
          }
          case 18: {
            configMap_.AddEntriesFrom(input, _repeated_configMap_codec);
            break;
          }
          case 26: {
            pod_.AddEntriesFrom(input, _repeated_pod_codec);
            break;
          }
          case 34: {
            serviceAccount_.AddEntriesFrom(input, _repeated_serviceAccount_codec);
            break;
          }
          case 42: {
            service_.AddEntriesFrom(input, _repeated_service_codec);
            break;
          }
          case 50: {
            daemonSet_.AddEntriesFrom(input, _repeated_daemonSet_codec);
            break;
          }
          case 58: {
            deployment_.AddEntriesFrom(input, _repeated_deployment_codec);
            break;
          }
          case 66: {
            replicaSet_.AddEntriesFrom(input, _repeated_replicaSet_codec);
            break;
          }
          case 74: {
            statefulSet_.AddEntriesFrom(input, _repeated_statefulSet_codec);
            break;
          }
          case 82: {
            horizontalPodAutoscaler_.AddEntriesFrom(input, _repeated_horizontalPodAutoscaler_codec);
            break;
          }
          case 90: {
            podTemplate_.AddEntriesFrom(input, _repeated_podTemplate_codec);
            break;
          }
          case 98: {
            secret_.AddEntriesFrom(input, _repeated_secret_codec);
            break;
          }
          case 106: {
            roleBinding_.AddEntriesFrom(input, _repeated_roleBinding_codec);
            break;
          }
          case 114: {
            role_.AddEntriesFrom(input, _repeated_role_codec);
            break;
          }
          case 122: {
            ingress_.AddEntriesFrom(input, _repeated_ingress_codec);
            break;
          }
          case 130: {
            networkPolicy_.AddEntriesFrom(input, _repeated_networkPolicy_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            binding_.AddEntriesFrom(ref input, _repeated_binding_codec);
            break;
          }
          case 18: {
            configMap_.AddEntriesFrom(ref input, _repeated_configMap_codec);
            break;
          }
          case 26: {
            pod_.AddEntriesFrom(ref input, _repeated_pod_codec);
            break;
          }
          case 34: {
            serviceAccount_.AddEntriesFrom(ref input, _repeated_serviceAccount_codec);
            break;
          }
          case 42: {
            service_.AddEntriesFrom(ref input, _repeated_service_codec);
            break;
          }
          case 50: {
            daemonSet_.AddEntriesFrom(ref input, _repeated_daemonSet_codec);
            break;
          }
          case 58: {
            deployment_.AddEntriesFrom(ref input, _repeated_deployment_codec);
            break;
          }
          case 66: {
            replicaSet_.AddEntriesFrom(ref input, _repeated_replicaSet_codec);
            break;
          }
          case 74: {
            statefulSet_.AddEntriesFrom(ref input, _repeated_statefulSet_codec);
            break;
          }
          case 82: {
            horizontalPodAutoscaler_.AddEntriesFrom(ref input, _repeated_horizontalPodAutoscaler_codec);
            break;
          }
          case 90: {
            podTemplate_.AddEntriesFrom(ref input, _repeated_podTemplate_codec);
            break;
          }
          case 98: {
            secret_.AddEntriesFrom(ref input, _repeated_secret_codec);
            break;
          }
          case 106: {
            roleBinding_.AddEntriesFrom(ref input, _repeated_roleBinding_codec);
            break;
          }
          case 114: {
            role_.AddEntriesFrom(ref input, _repeated_role_codec);
            break;
          }
          case 122: {
            ingress_.AddEntriesFrom(ref input, _repeated_ingress_codec);
            break;
          }
          case 130: {
            networkPolicy_.AddEntriesFrom(ref input, _repeated_networkPolicy_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
