name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Copy License
        run:
          cp ./License.md ./cli/

      - name: Set up Go
        uses: actions/setup-go@v3
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: v1.17.2
          args: release --clean
          workdir: cli
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICES_OAK9_PAT }}