name: Generate Language Files From Protos

on:
  push:
    branches:
    - main
    paths:
      - 'proto/**' # trigger workflow only for changes in proto directory

jobs:
  generate-protos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          
      - name: Install .NET 6.0 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x  
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v22.2/protoc-22.2-linux-x86_64.zip
          unzip protoc-22.2-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
          rm protoc-22.2-linux-x86_64.zip
      
      - name: Install MyPy
        run: |
          pip install mypy==1.1.1
          pip install mypy-extensions==1.0.0
          pip install mypy-protobuf==3.4.0
          pip install grpcio-tools==1.53.0
          pip install grpcio==1.53.0

      - name: Generate Python and MyPy files
        run: |
          python -m grpc_tools.protoc \
          -I proto \
          --proto_path=proto \
          --python_out=py/models \
          --grpc_python_out=py/models \
          --mypy_out=py/models \
          $(find proto/* -iname '*.proto')

      - name: Run Python Cleanup Script
        run: |
          cd py
          python python/post-generate-clean.py
          cd .. 
      
      - name: Generate C# and Typescript files
        run: |
          dotnet restore csharp/oak9.tython

          cd typescript
          cd src
          ## npm install
          ## cd ..
          ## cd ..

          cp ~/.nuget/packages/grpc.tools/2.53.0/tools/linux_x64/grpc_csharp_plugin $HOME/.local/bin/grpc_csharp_plugin
          ## cp -R typescript/src/node_modules/ $HOME/.local/node_modules

          protoc \
            --experimental_allow_proto3_optional \
            --proto_path=proto \
            --csharp_out=csharp/oak9.tython/models \
            --grpc_out=csharp/oak9.tython/models \
            --plugin=protoc-gen-grpc=$HOME/.local/bin/grpc_csharp_plugin \
            $(find proto -name '*.proto')

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-generated Protobuf files by ${{ github.event_name }} event at $(date -u +"%Y-%m-%dT%H:%M:%SZ") with commit message: ${{ github.event.head_commit.message }} by ${GITHUB_ACTOR}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{  secrets.SERVICES_OAK9_PAT  }}